import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import setupPlugins from "./plugins";
import "./style.css";
import "virtual:svg-icons-register";
import "uno.css";
import "element-plus/theme-chalk/dark/css-vars.css";
createApp(App).use(setupPlugins).use(createPinia()).use(router).mount("#app");
